"""Publish the canvas.diagram/v1 JSON Schema, generated from api/canvas_diagram.py.

The API is the only validator. The schema gives the renderers' JS tests and
the Canvas skill a reference without a second rule set to maintain. It covers
fields, types and limits, not the cross-field rules (see the format doc).

    python scripts/canvas_diagram_schema.py --write   # regenerate after a model change
    python scripts/canvas_diagram_schema.py           # print, for comparison

api/tests/test_canvas_diagram.py fails when the file and the models disagree.
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
OUTPUT = ROOT / "docs" / "canvas-diagram.schema.json"


def build() -> dict:
    from api.canvas_diagram import DiagramDocument

    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$comment": ("Generated by q-core scripts/canvas_diagram_schema.py. Do not edit by hand. "
                     "Cross-field rules (references, unique ids, activation balance, per-type "
                     "fields and totals) are enforced only by the API; see docs/canvas-diagram-format.md."),
        **DiagramDocument.model_json_schema(mode="validation"),
    }


def render() -> str:
    return json.dumps(build(), indent=2, sort_keys=True) + "\n"


if __name__ == "__main__":
    if "--write" in sys.argv:
        OUTPUT.write_text(render())
        print(f"wrote {OUTPUT}")
    else:
        sys.stdout.write(render())
